
package com.ruoyi.system.DPDinfo.pl.com.dpd.dpdinfoservices.events;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DPDInfoServicesObjEvents", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DPDInfoServicesObjEvents {


    /**
     * 
     * @param limit
     * @param language
     * @param authDataV1
     * @return
     *     returns pl.com.dpd.dpdinfoservices.events.CustomerEventsResponseV1
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEventsForCustomerV2", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForCustomerV2")
    @ResponseWrapper(localName = "getEventsForCustomerV2Response", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForCustomerV2Response")
    public CustomerEventsResponseV1 getEventsForCustomerV2(
        @WebParam(name = "limit", targetNamespace = "")
        Integer limit,
        @WebParam(name = "language", targetNamespace = "")
        String language,
        @WebParam(name = "authDataV1", targetNamespace = "")
        AuthDataV1 authDataV1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param waybill
     * @param eventsSelectType
     * @param language
     * @param authDataV1
     * @return
     *     returns pl.com.dpd.dpdinfoservices.events.CustomerEventsResponseV3
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEventsForWaybillV1", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForWaybillV1")
    @ResponseWrapper(localName = "getEventsForWaybillV1Response", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForWaybillV1Response")
    public CustomerEventsResponseV3 getEventsForWaybillV1(
        @WebParam(name = "waybill", targetNamespace = "")
        String waybill,
        @WebParam(name = "eventsSelectType", targetNamespace = "")
        EventsSelectTypeEnum eventsSelectType,
        @WebParam(name = "language", targetNamespace = "")
        String language,
        @WebParam(name = "authDataV1", targetNamespace = "")
        AuthDataV1 authDataV1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param limit
     * @param authDataV1
     * @return
     *     returns pl.com.dpd.dpdinfoservices.events.CustomerEventsResponseV1
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEventsForCustomerV1", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForCustomerV1")
    @ResponseWrapper(localName = "getEventsForCustomerV1Response", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForCustomerV1Response")
    public CustomerEventsResponseV1 getEventsForCustomerV1(
        @WebParam(name = "limit", targetNamespace = "")
        Integer limit,
        @WebParam(name = "authDataV1", targetNamespace = "")
        AuthDataV1 authDataV1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param limit
     * @param authDataV1
     * @return
     *     returns pl.com.dpd.dpdinfoservices.events.CustomerEventsResponseV2
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEventsForCustomerV3", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForCustomerV3")
    @ResponseWrapper(localName = "getEventsForCustomerV3Response", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForCustomerV3Response")
    public CustomerEventsResponseV2 getEventsForCustomerV3(
        @WebParam(name = "limit", targetNamespace = "")
        Integer limit,
        @WebParam(name = "authDataV1", targetNamespace = "")
        AuthDataV1 authDataV1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param limit
     * @param language
     * @param authDataV1
     * @return
     *     returns pl.com.dpd.dpdinfoservices.events.CustomerEventsResponseV2
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEventsForCustomerV4", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForCustomerV4")
    @ResponseWrapper(localName = "getEventsForCustomerV4Response", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.GetEventsForCustomerV4Response")
    public CustomerEventsResponseV2 getEventsForCustomerV4(
        @WebParam(name = "limit", targetNamespace = "")
        Integer limit,
        @WebParam(name = "language", targetNamespace = "")
        String language,
        @WebParam(name = "authDataV1", targetNamespace = "")
        AuthDataV1 authDataV1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param confirmId
     * @param authDataV1
     * @return
     *     returns java.lang.Boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "markEventsAsProcessedV1", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.MarkEventsAsProcessedV1")
    @ResponseWrapper(localName = "markEventsAsProcessedV1Response", targetNamespace = "http://events.dpdinfoservices.dpd.com.pl/", className = "pl.com.dpd.dpdinfoservices.events.MarkEventsAsProcessedV1Response")
    public Boolean markEventsAsProcessedV1(
        @WebParam(name = "confirmId", targetNamespace = "")
        String confirmId,
        @WebParam(name = "authDataV1", targetNamespace = "")
        AuthDataV1 authDataV1)
        throws Exception_Exception
    ;

}
