
package com.ruoyi.system.dpdservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-21T02:56:29.285+01:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "DeniedAccessWSException", targetNamespace = "http://dpdservices.dpd.com.pl/")
public class DeniedAccessWSException_Exception extends java.lang.Exception {
    
    private com.ruoyi.system.dpdservices.DeniedAccessWSException deniedAccessWSException;

    public DeniedAccessWSException_Exception() {
        super();
    }
    
    public DeniedAccessWSException_Exception(String message) {
        super(message);
    }
    
    public DeniedAccessWSException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DeniedAccessWSException_Exception(String message, com.ruoyi.system.dpdservices.DeniedAccessWSException deniedAccessWSException) {
        super(message);
        this.deniedAccessWSException = deniedAccessWSException;
    }

    public DeniedAccessWSException_Exception(String message, com.ruoyi.system.dpdservices.DeniedAccessWSException deniedAccessWSException, Throwable cause) {
        super(message, cause);
        this.deniedAccessWSException = deniedAccessWSException;
    }

    public com.ruoyi.system.dpdservices.DeniedAccessWSException getFaultInfo() {
        return this.deniedAccessWSException;
    }
}
