package com.ruoyi.system.dpdservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-21T02:56:29.297+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://dpdservices.dpd.com.pl/", name = "DPDPackageObjServices")
@XmlSeeAlso({ObjectFactory.class})
public interface DPDPackageObjServices {

    @WebMethod
    @RequestWrapper(localName = "generateProtocolV1", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateProtocolV1")
    @ResponseWrapper(localName = "generateProtocolV1Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateProtocolV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.DocumentGenerationResponseV1 generateProtocolV1(
            @WebParam(name = "dpdServicesParamsV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdServicesParamsV1 dpdServicesParamsV1,
            @WebParam(name = "outputDocFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocFormatDSPEnumV1 outputDocFormatV1,
            @WebParam(name = "outputDocPageFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocPageFormatDSPEnumV1 outputDocPageFormatV1,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateProtocolV2", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateProtocolV2")
    @ResponseWrapper(localName = "generateProtocolV2Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateProtocolV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.DocumentGenerationResponseV1 generateProtocolV2(
            @WebParam(name = "dpdServicesParamsV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdServicesParamsV1 dpdServicesParamsV1,
            @WebParam(name = "outputDocFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocFormatDSPEnumV1 outputDocFormatV1,
            @WebParam(name = "outputDocPageFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocPageFormatDSPEnumV1 outputDocPageFormatV1,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "packagesPickupCallV3", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.PackagesPickupCallV3")
    @ResponseWrapper(localName = "packagesPickupCallV3Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.PackagesPickupCallV3Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.PackagesPickupCallResponseV3 packagesPickupCallV3(
            @WebParam(name = "dpdPickupParamsV3", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdPickupCallParamsV3 dpdPickupParamsV3,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "packagesPickupCallV4", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.PackagesPickupCallV4")
    @ResponseWrapper(localName = "packagesPickupCallV4Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.PackagesPickupCallV4Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.PackagesPickupCallResponseV3 packagesPickupCallV4(
            @WebParam(name = "dpdPickupParamsV3", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdPickupCallParamsV3 dpdPickupParamsV3,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "packagesPickupCallV1", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.PackagesPickupCallV1")
    @ResponseWrapper(localName = "packagesPickupCallV1Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.PackagesPickupCallV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.PackagesPickupCallResponseV1 packagesPickupCallV1(
            @WebParam(name = "dpdPickupParamsV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdPickupCallParamsV1 dpdPickupParamsV1,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "packagesPickupCallV2", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.PackagesPickupCallV2")
    @ResponseWrapper(localName = "packagesPickupCallV2Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.PackagesPickupCallV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.PackagesPickupCallResponseV2 packagesPickupCallV2(
            @WebParam(name = "dpdPickupParamsV2", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdPickupCallParamsV2 dpdPickupParamsV2,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCourierOrderAvailabilityV1", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GetCourierOrderAvailabilityV1")
    @ResponseWrapper(localName = "getCourierOrderAvailabilityV1Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GetCourierOrderAvailabilityV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.GetCourierOrderAvailabilityResponseV1 getCourierOrderAvailabilityV1(
            @WebParam(name = "senderPlaceV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.SenderPlaceV1 senderPlaceV1,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws Exception_Exception, DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "appendParcelsToPackageV1", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.AppendParcelsToPackageV1")
    @ResponseWrapper(localName = "appendParcelsToPackageV1Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.AppendParcelsToPackageV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.ParcelsAppendResponseV1 appendParcelsToPackageV1(
            @WebParam(name = "parcelsAppend", targetNamespace = "")
                    com.ruoyi.system.dpdservices.ParcelsAppendV1 parcelsAppend,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateSpedLabelsV1", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateSpedLabelsV1")
    @ResponseWrapper(localName = "generateSpedLabelsV1Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateSpedLabelsV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.DocumentGenerationResponseV1 generateSpedLabelsV1(
            @WebParam(name = "dpdServicesParamsV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdServicesParamsV1 dpdServicesParamsV1,
            @WebParam(name = "outputDocFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocFormatDSPEnumV1 outputDocFormatV1,
            @WebParam(name = "outputDocPageFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocPageFormatDSPEnumV1 outputDocPageFormatV1,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateProtocolsWithDestinationsV1", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateProtocolsWithDestinationsV1")
    @ResponseWrapper(localName = "generateProtocolsWithDestinationsV1Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateProtocolsWithDestinationsV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.DocumentGenerationResponseV2 generateProtocolsWithDestinationsV1(
            @WebParam(name = "dpdServicesParamsV2", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdServicesParamsV2 dpdServicesParamsV2,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateProtocolsWithDestinationsV2", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateProtocolsWithDestinationsV2")
    @ResponseWrapper(localName = "generateProtocolsWithDestinationsV2Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateProtocolsWithDestinationsV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.DocumentGenerationResponseV2 generateProtocolsWithDestinationsV2(
            @WebParam(name = "dpdServicesParamsV2", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdServicesParamsV2 dpdServicesParamsV2,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateSpedLabelsV4", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateSpedLabelsV4")
    @ResponseWrapper(localName = "generateSpedLabelsV4Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateSpedLabelsV4Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.DocumentGenerationResponseV1 generateSpedLabelsV4(
            @WebParam(name = "dpdServicesParamsV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdServicesParamsV1 dpdServicesParamsV1,
            @WebParam(name = "outputDocFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocFormatDSPEnumV1 outputDocFormatV1,
            @WebParam(name = "outputDocPageFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocPageFormatDSPEnumV1 outputDocPageFormatV1,
            @WebParam(name = "outputLabelType", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputLabelTypeEnumV1 outputLabelType,
            @WebParam(name = "labelVariant", targetNamespace = "")
                    String labelVariant,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateSpedLabelsV3", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateSpedLabelsV3")
    @ResponseWrapper(localName = "generateSpedLabelsV3Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateSpedLabelsV3Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.DocumentGenerationResponseV1 generateSpedLabelsV3(
            @WebParam(name = "dpdServicesParamsV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdServicesParamsV1 dpdServicesParamsV1,
            @WebParam(name = "outputDocFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocFormatDSPEnumV1 outputDocFormatV1,
            @WebParam(name = "outputDocPageFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocPageFormatDSPEnumV1 outputDocPageFormatV1,
            @WebParam(name = "outputLabelType", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputLabelTypeEnumV1 outputLabelType,
            @WebParam(name = "labelVariant", targetNamespace = "")
                    String labelVariant,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generateSpedLabelsV2", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateSpedLabelsV2")
    @ResponseWrapper(localName = "generateSpedLabelsV2Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GenerateSpedLabelsV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.DocumentGenerationResponseV1 generateSpedLabelsV2(
            @WebParam(name = "dpdServicesParamsV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdServicesParamsV1 dpdServicesParamsV1,
            @WebParam(name = "outputDocFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocFormatDSPEnumV1 outputDocFormatV1,
            @WebParam(name = "outputDocPageFormatV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OutputDocPageFormatDSPEnumV1 outputDocPageFormatV1,
            @WebParam(name = "outputLabelTypeV2", targetNamespace = "")
                    String outputLabelTypeV2,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "importDeliveryBusinessEventV1", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.ImportDeliveryBusinessEventV1")
    @ResponseWrapper(localName = "importDeliveryBusinessEventV1Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.ImportDeliveryBusinessEventV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.ImportDeliveryBusinessEventResponseV1 importDeliveryBusinessEventV1(
            @WebParam(name = "dpdParcelBusinessEventV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.DpdParcelBusinessEventV1 dpdParcelBusinessEventV1,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DeniedAccessWSException_Exception, SchemaValidationException_Exception, DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findPostalCodeV1", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.FindPostalCodeV1")
    @ResponseWrapper(localName = "findPostalCodeV1Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.FindPostalCodeV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.FindPostalCodeResponseV1 findPostalCodeV1(
            @WebParam(name = "postalCodeV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.PostalCodeV1 postalCodeV1,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generatePackagesNumbersV1", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GeneratePackagesNumbersV1")
    @ResponseWrapper(localName = "generatePackagesNumbersV1Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GeneratePackagesNumbersV1Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.PackagesGenerationResponseV1 generatePackagesNumbersV1(
            @WebParam(name = "openUMLV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OpenUMLFeV1 openUMLV1,
            @WebParam(name = "pkgNumsGenerationPolicyV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.PkgNumsGenerationPolicyV1 pkgNumsGenerationPolicyV1,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generatePackagesNumbersV2", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GeneratePackagesNumbersV2")
    @ResponseWrapper(localName = "generatePackagesNumbersV2Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GeneratePackagesNumbersV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.PackagesGenerationResponseV2 generatePackagesNumbersV2(
            @WebParam(name = "openUMLV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OpenUMLFeV1 openUMLV1,
            @WebParam(name = "pkgNumsGenerationPolicyV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.PkgNumsGenerationPolicyV1 pkgNumsGenerationPolicyV1,
            @WebParam(name = "langCode", targetNamespace = "")
                    String langCode,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generatePackagesNumbersV3", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GeneratePackagesNumbersV3")
    @ResponseWrapper(localName = "generatePackagesNumbersV3Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GeneratePackagesNumbersV3Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.PackagesGenerationResponseV2 generatePackagesNumbersV3(
            @WebParam(name = "openUMLFeV2", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OpenUMLFeV2 openUMLFeV2,
            @WebParam(name = "pkgNumsGenerationPolicyV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.PkgNumsGenerationPolicyV1 pkgNumsGenerationPolicyV1,
            @WebParam(name = "langCode", targetNamespace = "")
                    String langCode,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "generatePackagesNumbersV4", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GeneratePackagesNumbersV4")
    @ResponseWrapper(localName = "generatePackagesNumbersV4Response", targetNamespace = "http://dpdservices.dpd.com.pl/", className = "com.ruoyi.system.dpdservices.GeneratePackagesNumbersV4Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.ruoyi.system.dpdservices.PackagesGenerationResponseV2 generatePackagesNumbersV4(
            @WebParam(name = "openUMLFeV3", targetNamespace = "")
                    com.ruoyi.system.dpdservices.OpenUMLFeV3 openUMLFeV3,
            @WebParam(name = "pkgNumsGenerationPolicyV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.PkgNumsGenerationPolicyV1 pkgNumsGenerationPolicyV1,
            @WebParam(name = "langCode", targetNamespace = "")
                    String langCode,
            @WebParam(name = "authDataV1", targetNamespace = "")
                    com.ruoyi.system.dpdservices.AuthDataV1 authDataV1
    ) throws DPDServiceException_Exception;
}
