
package com.ruoyi.system.dpdservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-21T02:56:29.253+01:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "DPDServiceException", targetNamespace = "http://dpdservices.dpd.com.pl/")
public class DPDServiceException_Exception extends java.lang.Exception {
    
    private com.ruoyi.system.dpdservices.DPDServiceException dpdServiceException;

    public DPDServiceException_Exception() {
        super();
    }
    
    public DPDServiceException_Exception(String message) {
        super(message);
    }
    
    public DPDServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DPDServiceException_Exception(String message, com.ruoyi.system.dpdservices.DPDServiceException dpdServiceException) {
        super(message);
        this.dpdServiceException = dpdServiceException;
    }

    public DPDServiceException_Exception(String message, com.ruoyi.system.dpdservices.DPDServiceException dpdServiceException, Throwable cause) {
        super(message, cause);
        this.dpdServiceException = dpdServiceException;
    }

    public com.ruoyi.system.dpdservices.DPDServiceException getFaultInfo() {
        return this.dpdServiceException;
    }
}
