
package com.ruoyi.system.dpdservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-21T02:56:29.279+01:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "Exception", targetNamespace = "http://dpdservices.dpd.com.pl/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.ruoyi.system.dpdservices.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.ruoyi.system.dpdservices.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.ruoyi.system.dpdservices.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.ruoyi.system.dpdservices.Exception getFaultInfo() {
        return this.exception;
    }
}
