
package com.ruoyi.system.dpdservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-21T02:56:29.291+01:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "SchemaValidationException", targetNamespace = "http://dpdservices.dpd.com.pl/")
public class SchemaValidationException_Exception extends java.lang.Exception {
    
    private com.ruoyi.system.dpdservices.SchemaValidationException schemaValidationException;

    public SchemaValidationException_Exception() {
        super();
    }
    
    public SchemaValidationException_Exception(String message) {
        super(message);
    }
    
    public SchemaValidationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SchemaValidationException_Exception(String message, com.ruoyi.system.dpdservices.SchemaValidationException schemaValidationException) {
        super(message);
        this.schemaValidationException = schemaValidationException;
    }

    public SchemaValidationException_Exception(String message, com.ruoyi.system.dpdservices.SchemaValidationException schemaValidationException, Throwable cause) {
        super(message, cause);
        this.schemaValidationException = schemaValidationException;
    }

    public com.ruoyi.system.dpdservices.SchemaValidationException getFaultInfo() {
        return this.schemaValidationException;
    }
}
